twig:
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': images
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
